version: 'latest'

services:
  database_ignite:
    image: postgres
    hostname: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mazzillio
      - POSTGRES_PASSWORD=db1234
      - POSTGRES_DB=rentx
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - "5432"
  db_test:
    image: postgres
    hostname: postgres
    environment: 
      - POSTGRES_DB=mazzillio
      - POSTGRES_USER=db1234
      - POSTGRES_PASSWORD=rentx_test
    ports:
    - 5433:5432
volumes:
  postgres-data: