version: 'latest'

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mazzillio
      - POSTGRES_PASSWORD=db1234
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
   build: .
   container_name: apprentex
   ports:
     - 3500:3500
   volumes:
    - .:/usr/app
   links:
     - database_ignite
   depends_on:
     - database_ignite
volumes:
  pgdata: